server:
  port: 9010

spring:
  application:
    name: order-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.100.5:8848
    sentinel:
      transport:
        dashboard: localhost:8101
        port: 8701

feign:
  sentinel:
    enabled: true

